#!/usr/bin/env python3
"""Embed game assets as base64 data URIs into js/assetData.js.

Run from anywhere:  python3 tools/embed_assets.py
Re-run whenever the team list or sprite selection changes.
"""
import base64
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ASSETS = os.path.join(ROOT, "assets")
OUT = os.path.join(ROOT, "js", "assetData.js")

SPORTS = os.path.join(ASSETS, "kenney_sports-pack", "PNG")
FLAGS = os.path.join(ASSETS, "kenney_flag-pack", "Default")

# ISO codes for the 16 selectable nations (must match js/teams.js)
TEAM_FLAGS = [
    "US", "MX", "CA", "BR", "AR", "FR", "GB_ENG", "ES",
    "DE", "PT", "NL", "IT", "JP", "MA", "HR", "BE",
]


def b64(path):
    with open(path, "rb") as f:
        return "data:image/png;base64," + base64.b64encode(f.read()).decode()


def main():
    entries = {}

    # Player bodies: the Blue set is the recolor source (shirt hues swapped at
    # runtime). Variants 1-10 are full bodies with different skin/hair.
    for i in range(1, 11):
        entries[f"char{i}"] = b64(os.path.join(SPORTS, "Blue", f"characterBlue ({i}).png"))

    entries["ball"] = b64(os.path.join(SPORTS, "Equipment", "ball_soccer1.png"))

    for code in TEAM_FLAGS:
        path = os.path.join(FLAGS, f"{code}.png")
        if not os.path.exists(path):
            raise SystemExit(f"missing flag: {path}")
        entries[f"flag_{code}"] = b64(path)

    lines = ["// GENERATED by tools/embed_assets.py - do not edit by hand.",
             "WC.ASSET_DATA = {"]
    for k, v in entries.items():
        lines.append(f'  "{k}": "{v}",')
    lines.append("};")

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as f:
        f.write("\n".join(lines) + "\n")
    size = os.path.getsize(OUT)
    print(f"wrote {OUT} ({size/1024:.1f} KB, {len(entries)} assets)")


if __name__ == "__main__":
    main()
